### ISSUE TITLE
Link in "Use the Author Tools web service" line on <https://authors.ietf.org/en/upgrading-from-v2> doesn't work

### ISSUE THREAD

**Issue by lbartholomew-rpc** [ietf/authors.ietf.org#49]
The link in the "Use the Author Tools web service" line on <https://authors.ietf.org/en/upgrading-from-v2> doesn't work.

**Comment by JayDaley** [comment]
Fixed

**Comment by lbartholomew-rpc** [comment]
Thank you, Jay!

RFC Editor/lb
