### ISSUE TITLE
Make it clear that the `internet-draft-template` also works with XML files

### ISSUE THREAD

**Issue by ralienpp** [ietf/authors.ietf.org#51]
After tinkering with the automated Github workflow to help out a colleague, I concluded that a great deal of time could be saved if it were clearer that the same mechanism handles XML files too.

I believe the current information is somewhat misleading, because if my goal is to write a draft in XML, when I read this in [the guide](https://authors.ietf.org/en/collaborative-editing) "... are a pair of tools that work together to provide an automated Markdown I-D build system in GitHub" - I remove these candidates from my mental search-space because "ah.. these are for Markdown, I need the same, but for XML".

After some trial and error and source reading, I found that everything works for XML too, I only had to add my draft to the root directory of the repository and everything worked out of the box!

**Comment by ajeanmahoney** [comment]
Hi @ralienpp, thanks for the feedback! You are correct that this should be clarified. There should also be an update to the [Drafting in XML](https://authors.ietf.org/en/drafting-in-xml) page, which would basically be a copy of the template info that's found on the [Drafting in Markdown](https://authors.ietf.org/drafting-in-markdown) page.

**Comment by JayDaley** [comment]
Changes now made to https://authors.ietf.org/en/collaborative-editing and https://authors.ietf.org/drafting-in-xml
